name: SnowTracker
options:
  bundleIdPrefix: com.wouterdevriendt
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.8.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS.git
    from: 8.0.0
  Get:
    url: https://github.com/CreateAPI/Get.git
    from: 2.1.0
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: 12.1.0
  KeychainSwift:
    url: https://github.com/evgenyneu/keychain-swift.git
    from: 20.0.0

targets:
  SnowTracker:
    type: application
    platform: iOS
    sources:
      - path: SnowTracker/SnowTracker/Sources
      - path: SnowTracker/SnowTracker/Resources
    settings:
      base:
        INFOPLIST_FILE: SnowTracker/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.wouterdevriendt.snowtracker
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: N324UX8D9M
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: SnowTracker/SnowTracker.entitlements
      properties:
        aps-environment: development
        com.apple.security.application-groups:
          - group.com.wouterdevriendt.snowtracker
        com.apple.developer.applesignin:
          - Default
    dependencies:
      - package: Alamofire
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: Get
      - package: Nuke
      - package: KeychainSwift
      - target: SnowTrackerWidgetExtension
    info:
      path: SnowTracker/Info.plist
      properties:
        CFBundleName: Snow Tracker
        CFBundleDisplayName: Snow Tracker
        CFBundleShortVersionString: "1.1.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: AccentColor
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        # Privacy - Location Usage
        NSLocationWhenInUseUsageDescription: "Snow Tracker uses your location to show nearby ski resorts and calculate distances to resorts."
        # App Store compliance
        ITSAppUsesNonExemptEncryption: false
        # Google Sign-In configuration
        GIDClientID: 269334695221-p2i31pdp3n7ms7o7rpf6cb3vsdmc4ohs.apps.googleusercontent.com
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - com.googleusercontent.apps.269334695221-p2i31pdp3n7ms7o7rpf6cb3vsdmc4ohs

  SnowTrackerWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: SnowTrackerWidget
    settings:
      base:
        INFOPLIST_FILE: SnowTrackerWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.wouterdevriendt.snowtracker.widget
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: N324UX8D9M
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
    entitlements:
      path: SnowTrackerWidget/SnowTrackerWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.wouterdevriendt.snowtracker
    info:
      path: SnowTrackerWidget/Info.plist
      properties:
        CFBundleName: Snow Tracker Widget
        CFBundleDisplayName: Snow Tracker Widget
        CFBundleShortVersionString: "1.1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  SnowTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SnowTracker/SnowTrackerTests
        optional: true
    dependencies:
      - target: SnowTracker
    settings:
      base:
        INFOPLIST_FILE: SnowTracker/SnowTrackerTests/Info.plist

  SnowTrackerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SnowTracker/SnowTrackerUITests
        optional: true
    dependencies:
      - target: SnowTracker
    settings:
      base:
        INFOPLIST_FILE: SnowTracker/SnowTrackerUITests/Info.plist

schemes:
  SnowTracker:
    build:
      targets:
        SnowTracker: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SnowTrackerTests
        - SnowTrackerUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
